---
name: 🧪 Container Test

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  container-test:
    name: Container Test
    permissions:
      contents: read
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-container-test.yml@949059b3345aaf08170204e57a010324f03a985b # v4.5.0
