---
name: Scan Image

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  scan-image:
    name: Scan Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Build Image
        id: build_image
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        with:
          push: false
          load: true
          tags: analytical-platform-rshiny-open-source-base

      - name: Scan Image
        id: scan_image
        uses: aquasecurity/trivy-action@a20de5420d57c4102486cdd9578b45609c99d7eb # v0.26.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
        with:
          image-ref: analytical-platform-rshiny-open-source-base
          exit-code: 1
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL
          limit-severities-for-sarif: true

      - name: Upload SARIF
        if: always()
        id: upload_sarif
        uses: github/codeql-action/upload-sarif@461ef6c76dfe95d5c364de2f431ddbd31a417628 # v3.26.9
        with:
          sarif_file: trivy-results.sarif

      - name: Scan Image (On SARIF Scan Failure)
        if: failure() && steps.scan_image.outcome == 'failure'
        id: scan_image_on_failure
        uses: aquasecurity/trivy-action@a20de5420d57c4102486cdd9578b45609c99d7eb # v0.26.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
        with:
          image-ref: analytical-platform-rshiny-open-source-base
          exit-code: 1
          format: table
          severity: CRITICAL
